openapi: 3.0.3
info:
  title: Schwab Real-Time GEX API
  description: API for real-time Gamma Exposure (GEX) calculations using Schwab market data
  version: 1.0.0
  contact:
    name: Data Pipeline Team
    email: team@data-pipeline.com

servers:
  - url: http://localhost:8000/api/v1
    description: Development server
  - url: https://api.data-pipeline.com/v1
    description: Production server

security:
  - bearerAuth: []

paths:
  /health:
    get:
      summary: Health check endpoint
      description: Check the health status of the GEX service
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

  /gex/{symbol}:
    get:
      summary: Get current GEX calculation for a symbol
      description: Retrieve the latest Gamma Exposure calculation for a given symbol
      parameters:
        - name: symbol
          in: path
          required: true
          schema:
            type: string
            pattern: '^[A-Z]{1,5}(\.[A-Z]{1,2})?$'
          description: Stock symbol (e.g., SPY, AAPL)
        - name: include_options
          in: query
          schema:
            type: boolean
            default: false
          description: Include detailed options data in response
      responses:
        '200':
          description: Successful GEX calculation retrieval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GEXResponse'
        '404':
          description: Symbol not found or no data available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: Service temporarily unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /gex/{symbol}/history:
    get:
      summary: Get historical GEX calculations
      description: Retrieve historical Gamma Exposure calculations for a symbol
      parameters:
        - name: symbol
          in: path
          required: true
          schema:
            type: string
            pattern: '^[A-Z]{1,5}(\.[A-Z]{1,2})?$'
          description: Stock symbol
        - name: start_date
          in: query
          schema:
            type: string
            format: date-time
          description: Start date for historical data (ISO 8601 format)
        - name: end_date
          in: query
          schema:
            type: string
            format: date-time
          description: End date for historical data (ISO 8601 format)
        - name: interval
          in: query
          schema:
            type: string
            enum: [1m, 5m, 15m, 1h, 1d]
            default: 5m
          description: Time interval between data points
      responses:
        '200':
          description: Successful historical data retrieval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GEXHistoryResponse'
        '400':
          description: Invalid date range or parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /market/{symbol}:
    get:
      summary: Get current market data for a symbol
      description: Retrieve real-time market data for a given symbol
      parameters:
        - name: symbol
          in: path
          required: true
          schema:
            type: string
            pattern: '^[A-Z]{1,5}(\.[A-Z]{1,2})?$'
          description: Stock symbol
      responses:
        '200':
          description: Successful market data retrieval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketDataResponse'
        '404':
          description: Symbol not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /options/{symbol}:
    get:
      summary: Get options chain for a symbol
      description: Retrieve current options chain data for GEX calculations
      parameters:
        - name: symbol
          in: path
          required: true
          schema:
            type: string
            pattern: '^[A-Z]{1,5}(\.[A-Z]{1,2})?$'
          description: Underlying stock symbol
        - name: expiration_date
          in: query
          schema:
            type: string
            format: date
          description: Specific expiration date (YYYY-MM-DD format)
        - name: option_type
          in: query
          schema:
            type: string
            enum: [call, put, both]
            default: both
          description: Type of options to retrieve
      responses:
        '200':
          description: Successful options data retrieval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OptionsResponse'
        '404':
          description: Symbol not found or no options available
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /connection/status:
    get:
      summary: Get Schwab connection status
      description: Check the current status of the Schwab API connection
      responses:
        '200':
          description: Connection status retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectionStatusResponse'

  /cache/stats:
    get:
      summary: Get cache statistics
      description: Retrieve statistics about the data cache performance
      responses:
        '200':
          description: Cache statistics retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CacheStatsResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          enum: [healthy, degraded, unhealthy]
        timestamp:
          type: string
          format: date-time
        version:
          type: string
        uptime_seconds:
          type: number
        services:
          type: object
          properties:
            schwab_api:
              type: string
              enum: [connected, disconnected, error]
            redis_cache:
              type: string
              enum: [available, unavailable]
            duckdb_storage:
              type: string
              enum: [available, unavailable]

    GEXResponse:
      type: object
      properties:
        symbol:
          type: string
        calculation_timestamp:
          type: string
          format: date-time
        data_timestamp:
          type: string
          format: date-time
        spot_price:
          type: number
          format: float
        total_gamma:
          type: number
          format: float
        gamma_flip_price:
          type: number
          format: float
          nullable: true
        max_gamma_price:
          type: number
          format: float
          nullable: true
        call_gamma:
          type: number
          format: float
        put_gamma:
          type: number
          format: float
        net_gamma:
          type: number
          format: float
        options_count:
          type: integer
        confidence_score:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
        options_data:
          type: array
          items:
            $ref: '#/components/schemas/OptionData'
          nullable: true

    GEXHistoryResponse:
      type: object
      properties:
        symbol:
          type: string
        interval:
          type: string
        data_points:
          type: array
          items:
            $ref: '#/components/schemas/GEXDataPoint'

    GEXDataPoint:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        spot_price:
          type: number
          format: float
        total_gamma:
          type: number
          format: float
        gamma_flip_price:
          type: number
          format: float
          nullable: true
        confidence_score:
          type: number
          format: float

    MarketDataResponse:
      type: object
      properties:
        symbol:
          type: string
        price:
          type: number
          format: float
        volume:
          type: integer
        timestamp:
          type: string
          format: date-time
        bid:
          type: number
          format: float
          nullable: true
        ask:
          type: number
          format: float
          nullable: true
        bid_size:
          type: integer
          nullable: true
        ask_size:
          type: integer
          nullable: true
        day_high:
          type: number
          format: float
          nullable: true
        day_low:
          type: number
          format: float
          nullable: true
        prev_close:
          type: number
          format: float
          nullable: true
        data_quality:
          type: string
          enum: [realtime, delayed, stale]

    OptionsResponse:
      type: object
      properties:
        symbol:
          type: string
        expiration_dates:
          type: array
          items:
            type: string
            format: date
        options:
          type: array
          items:
            $ref: '#/components/schemas/OptionData'

    OptionData:
      type: object
      properties:
        option_symbol:
          type: string
        strike_price:
          type: number
          format: float
        expiration_date:
          type: string
          format: date
        option_type:
          type: string
          enum: [call, put]
        bid:
          type: number
          format: float
        ask:
          type: number
          format: float
        last_price:
          type: number
          format: float
        volume:
          type: integer
        open_interest:
          type: integer
        implied_volatility:
          type: number
          format: float
          nullable: true
        delta:
          type: number
          format: float
          nullable: true
        gamma:
          type: number
          format: float
          nullable: true
        theta:
          type: number
          format: float
          nullable: true
        vega:
          type: number
          format: float
          nullable: true
        rho:
          type: number
          format: float
          nullable: true
        timestamp:
          type: string
          format: date-time

    ConnectionStatusResponse:
      type: object
      properties:
        status:
          type: string
          enum: [connected, disconnected, authenticating, error]
        last_connected_at:
          type: string
          format: date-time
          nullable: true
        reconnect_attempts:
          type: integer
        message:
          type: string
          nullable: true

    CacheStatsResponse:
      type: object
      properties:
        total_entries:
          type: integer
        cache_hit_rate:
          type: number
          format: float
        memory_usage_bytes:
          type: integer
        oldest_entry_age_seconds:
          type: integer
        newest_entry_age_seconds:
          type: integer
        data_types:
          type: object
          properties:
            market_data:
              type: integer
            options_data:
              type: integer
            gex_results:
              type: integer

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time
        request_id:
          type: string
          nullable: true
        details:
          type: object
          nullable: true
      required:
        - error
        - message
        - timestamp